version: '2'

services:
   mysql-container:
     image: mysql:5.7
     ports:
      - 3306:3306
     environment:
      MYSQL_DATABASE: latatuadora_core
      MYSQL_USER: latatuadora
      MYSQL_PASSWORD: latatuadora
      MYSQL_ROOT_PASSWORD: latatuadora